---
version: "3.7"
services:
  drgon-server:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.drgon-server
    image: ghcr.io/geocml/drgon:server
    ports:
      - "8000:8000"
    hostname: drgon-server
    environment:
      DRGON_POSTGRES_ADMIN_PASSWORD: ${DRGON_POSTGRES_ADMIN_PASSWORD}
    networks:
      - drgon-network
  drgon-postgres:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.drgon-postgres
    image: ghcr.io/geocml/drgon:postgres
    ports:
      - "${DRGON_POSTGRES_PORT}:5433"
    hostname: drgon-postgres
    environment:
      DRGON_POSTGRES_ADMIN_PASSWORD: ${DRGON_POSTGRES_ADMIN_PASSWORD}
    networks:
      - drgon-network
networks:
  drgon-network:
    external: true
    driver: bridge
